version: '3'

services:
  literalura:
    container_name: "container"
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://literalura_pg:5432/literalura
      DB_USER: postgres
      DB_PASSWORD: root   
    restart: always
    depends_on:
      - literalura_pg

  literalura_bd:
    container_name: "literalura_db"
    image: mysql:8.3.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: literalura
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10

  literalura_pg:
    container_name: "literalura_pg"
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: literalura
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    restart: always
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: literalura_bd
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - literalura_bd
    restart: always
    
  spring:
  task:
    execution:
      pool:
        core-size: 20
        max-size: 100
        keep-alive: 10s
        queue-capacity: 500
        allow-core-thread-timeout: true

volumes:
    mysql-data:
    postgres-data:  