version: '3'

services:
  literalura:
    container_name: "container"
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://literalura_pg:5432/literalura
      DB_USER: postgres
      DB_PASSWORD: root   
    restart: always
    depends_on:
      - literalura_pg

  literalura_pg:
    container_name: "literalura_pg"
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: literalura
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    restart: always

volumes:
    postgres-data:  